CREATE DATABASE IF NOT EXISTS exchange;
CREATE DATABASE IF NOT EXISTS exchange_test;
  
CREATE TABLE IF NOT EXISTS users (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255)  NOT NULL UNIQUE, 
  `username` VARCHAR(63)  NOT NULL UNIQUE, 
  `password` VARCHAR(255)  NOT NULL, 
  `profilePictureUrl` TEXT, 
  `citySlug` VARCHAR(255)  NOT NULL, 
  `allowOnlineTransactions` TINYINT(1) NOT NULL DEFAULT 1,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deletedAt` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`) 
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS exchanges (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `userId` INTEGER NOT NULL, 
  `website` VARCHAR(255)  NOT NULL, 
  `createdAt` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deletedAt` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`) ,
  CONSTRAINT `user-id-exchanges-key` FOREIGN KEY (`userid`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS cities (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(255)  NOT NULL UNIQUE,
  `name` VARCHAR(255)  NOT NULL, 
  `country` VARCHAR(255)  NOT NULL, 
  `createdAt` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deletedAt` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`) 
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS coins (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(255)  NOT NULL, -- fiat, crypto
  `name` VARCHAR(255)  NOT NULL UNIQUE, 
  `symbol` VARCHAR(255)  NOT NULL UNIQUE, 
  `logoUrl` TEXT,
  `createdAt` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deletedAt` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`) 
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4 COLLATE=utf8mb4_bin;


CREATE TABLE IF NOT EXISTS offers (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `userId` INTEGER NOT NULL, 
  `citySlug` VARCHAR(255) NOT NULL, 
  `sourceCoinSymbol` VARCHAR(255) NOT NULL,
  `destCoinSymbol` VARCHAR(255) NOT NULL, 
  `minAmount` INTEGER, 
  `amount` INTEGER NOT NULL, 
  `wantedPricePerUnit` DECIMAL(10,2), 
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deletedAt` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`) ,
  CONSTRAINT `user-id-offer-key` FOREIGN KEY (`userid`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
  ) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS offerlookups (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `citySlug` VARCHAR(255) NOT NULL, 
  `sourceCoinSymbol` VARCHAR(255) NOT NULL, 
  `destCoinSymbol` VARCHAR(255) NOT NULL,
  `createdAt` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deletedAt` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
  ) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS userrates (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `userId` INTEGER NOT NULL,
  -- `offerid` INTEGER NOT NULL,
  `raterUserId` INTEGER NOT NULL, 
  `grade` INTEGER NOT NULL,  
  `createdAt` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deletedAt` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`) ,
  -- CONSTRAINT `offer-id-rates-key` FOREIGN KEY (`offerid`) REFERENCES `offers` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `user-id-rates-key` FOREIGN KEY (`userid`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `rater-user-id-rates-key` FOREIGN KEY (`rateruserid`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4 COLLATE=utf8mb4_bin;

