version: '3'

services:

  db:
    image: mysql:5.7
    ports:
        - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: p4SSW0rd
      MYSQL_DATABASE: exchange
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbp4ss 

  api:
    build: .
    ports:
        - "3000:3000"
    depends_on:
        - "db"
    environment:
      NODE_ENV: docker
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: p4SSW0rd
      DB_SCHEMAS: exchange
      DB_PORT: 3306
      FLYWAY_URL: jdbc:mysql://db:3306 
      FLYWAY_USER: root
      FLYWAY_PASSWORD: p4SSW0rd
      FLYWAY_SCHEMAS: exchange